apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: eventer
  labels:
    app: eventer
  name: eventer
  namespace: kube-system
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: eventer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
      labels:
        app: eventer
    spec:
      serviceAccountName: admin
      containers:
      - name: eventer
        image: xxxx.xxx.com/eventer:v1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 300Mi
        env:
        - name: CLUSTER_NAME
          value: '测试集群'
        - name: DING_ROBOT
          value: 'https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxxx'
        - name: LEVEL
          value: 'Warning'
        - name: TIMES
          value: '10'
        - name: INTERVAL
          value: '180'
        - name: NODE_AT_ALL
          value: 'True'

