apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: eventer
  labels:
    app: eventer
  name: eventer
  namespace: kube-system
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: eventer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
      labels:
        app: eventer
    spec:
      serviceAccountName: admin
      containers:
      - name: eventer
        image: xxxx.xxx.com/eventer:v1.0.5
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 300Mi
        command:
          - python3
          - /opt/eventer.py
          - '--ding-robot=https://oapi.dingtalk.com/robot/send?access_token=xxxxxx'
          - '--stdout'
          - '--in-cluster'
          - '--log-level=WARNING'
          - '--level=Warning'
          - '--cluster-name=生产集群'
          - '--es-host=10.30.1.185:9200'

